### ISSUE TITLE
Npm run watch error

### ISSUE THREAD

**Issue by Shahid87** [Hujjat/shopify-starter-theme#6]
I cloned the theme from your github repository. after that, I run command npm install and install node_module but when I run npm run watch command it shows errors below to see the attached screenshot 

![image](https://user-images.githubusercontent.com/5441243/80670268-e561cd00-8abf-11ea-8f82-35ffc0bb87e6.png)

**Comment by Shahid87** [comment]
I found that error solution run this command "npm install --global cross-env " and now my npm run watch is working :)

**Comment by Shahid87** [comment]
I found that error solution run this command "npm install --global cross-env " and now my npm run watch is working :)

**Comment by hayat824** [comment]
Shahid,How you solve this issue?

**Comment by Shahid87** [comment]
> Shahid, How you solve this issue?

Run npm update to updated all dependencies
I hope this may help you

**Comment by hayat824** [comment]
Thank you.   " npm install cross-env  "  solved my issue.

**Comment by asifbilalzerogravity** [comment]
I re cloned my repo and re install node. it works fine for me now.
